# Generated by Django 3.0.8 on 2020-07-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_olxitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='olxitem',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
