# Generated by Django 3.0.8 on 2020-07-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200717_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_nasc', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
    ]
